name: 'Generate coverage report'

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  coverage:

    runs-on: [ubuntu-latest]
    name: Coverage on Ubuntu

    steps:
      - uses: actions/checkout@v2.4.0
      - name: Set up JDK 1
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Generate coverage with JaCoCo
        run: mvn -V -ntp clean verify jacoco:prepare-agent test integration-test jacoco:report --file pom.xml '-Dgpg.skip'

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{secrets.CODECOV_TOKEN}}
